[package]
name = "Automata-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_log = "0.2.0"
log = "0.4.17"
eframe = "0.19.0"
egui = "0.19.0"
wasm-bindgen = "0.2.83"
